name: Release Commons(HG)

on:
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'apache/hugegraph-commons'
      repository_branch:
        required: true
        default: 'release-1.0.0'
      release_version:
        required: true
        description: release_version - only influence SVN
        default: '1.0.0'
      deploy_maven:
        required: true
        type: boolean
        description: publish to maven nexus repo
        default: false
      deploy_svn:
        required: true
        type: boolean
        description: publish to apache svn
        default: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
       
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          # refer: github.com/crazy-max/ghaction-import-gpg#prerequisites
          # MacOS: gpg --armor --export-secret-key joe@foo.bar | pbcopy
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_url }}
          ref: ${{ inputs.repository_branch }}
          fetch-depth: 2

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Replace maven settings
        run: mkdir -p ~/.m2 && echo '${{ secrets.M2_SETTINGS }}' > ~/.m2/settings.xml

      - name: Package Only
        if: ${{ !inputs.deploy_maven }}
        run: (echo "just building" && mvn clean package -Papache-release -DskipTests -ntp -e) || exit

      - name: Package & Release to maven
        if: ${{ inputs.deploy_maven }}
        run: (echo "deploy to maven" && mvn clean deploy -Papache-release -DskipTests -e) || exit        
        
      - name: Release to svn
        if: ${{ inputs.deploy_svn }}
        run: hugegraph-dist/scripts/apache-release.sh ${{ inputs.release_version }} ${{ secrets.RELEASE_USERNAME }} ${{ secrets.RELEASE_PASSWORD }}
